
data_quality_check:
	python aipc_plain_execution data_quality_check
	
run_drift_detection:
	python aipc_plain_execution.py run_drift_detection

train_model:
	python aipc_plain_execution.py train_model

evaluate_model:
	python aipc_plain_execution.py evaluate_model